name: Send Line Notification

on:
  schedule:
    - cron: '*/1 * * * *' # 每隔1分鐘

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install yfinance requests

      - name: Execute Python script
        run: python your_script.py  # 替換成您的Python腳本文件名

